# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "ZPeZjf46dYylFWbY22vYVW6nFpBK5+PHAbTZsVgu7su24plAGNYNfTnjaP92Bs/hxOekjH2v6WoQze7O/J509r9cOLsmUVSwdE2ac8c4AlRJk4zshXf55+Q+PlgtRV7o/RYBcYyXk3B506dZZ7aDWH0wWChmtZVY/UdjGjyNp0JxzYAFv+w1dSGOce70UU6wUTKSEqABdQGhNAADt8iNTI6NZGabDUAOCO/HufEO+kqE/NJk9mPzVwM57kDCdA6igYgkJfJ171v9IZ3vmxSxxp3lz9utQBj03GFRsiGf4CsXZa0YpqgmgSW+afqR8ivAChUByvymPBFi2U1JjbCi49UlHwlKdqACpI9KH3vNSToe9fMlvTuCHz3Tb4OhB1+CQBWeoUPj0KuHDSrN+TJKANFConhp1MfCVraOA4LQyVzUpODqqZHxoxAtTNMIIMJUj9uYn58w9nG9ufJRqfwPa1sbVfcf2YlN8ET1VRHY4nhuMfQJB7xESjFAuWU+QvR6isxIXiZ1HVEsSxeMI1PQn15ukdyFGf6w1OgZPqqA0rqbp7XFyr8Pv8zrIWwslFwZvkIfRuLHuLChI6gN5nsMn14G2lXRiTWnjRMwN+h6B8bKmBiTV7naodII5Ad1t0+t1Bl3xH3CR4ZN3WB8kfWe3m3kDG0xeu2AQ4c5U4HH4iQ="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "nilMiGrTM7n1HosIc0EKnh7jR7MFPEo5453W2X6Ipy8JHzVW2Sf8et5p0hdi4+D+yuG7gG9C0gg8zXwPNcU387Ihpf8gpzZMZYXwuogE4GzCPry29UuEOebShM/1rDW2apoT8+XAwSSMR05dlZNkH7GL2Wv9O90KEQKnNG/0t5fxpkCBOwPLEn96pk7NpsTWDpQprfUk2sREjABNs3juLM738Bc37ObL30dZpq74sdxoiRcSPY7QAQnSrmQewMWnJFr6JumWLZwk5pszxx95E7Z6GqnlDvAblnOlAWGdTrfMCaB4xjDgyYtIJart9InpBw9MHm7baSBaHWfU/FBix/AdrVwzPKYN0WZwjoi/oG5yhveMbwOywFRNli5KMGXuBkYzdD5KUQSybfs4LBUMiFg1HeNsueRnIe+XteL8amrsRum14yxhBVHU1Tou//u4Socs7SKbIH+Mz8SHJaRZbWbjZOICCw5VAyECdS2sMKgKLzaieyQ28otM3nCzBdrWT2FqaekaL807SuvYs0i6m5HcIOiWyc/q+ba9HYW7jiWQsxUIkf4RGgRUhKDCaZrocWLT4imxjbAR75SrVD/0ACpZZ7z4Yzx5v6jWbYWpdME5MiZQzI21U+RLGOitKQBz65OFyyRXhT2Gl0YiAntoAEAr6PhbRQauMPKbKyOGySM="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "XFMYoxKrfuqa4FfqnziNXJui0KAWZp4/s3q3A7PG64TbOw70+oNvlB2uOfhNEs3oDncWLtk7+HAlH7xhqWYlRqZhM9e9dmKEt4hJB4K2XBsVKfN34gRi81NN7znNYh8DrBecTg+JLNOCSMJGX/1s8ZvwcnUmo8jk1gitHnxPJLjlaO1EFxkP+CAs7rfp/nk1TnfQ5RRUEBaRhu1vNVvM/ktQUpGJN4GfatlBPfF+e6BGns6JYJIwXgOwUkKV4osezNHXR/7agNlt6XyLLdCP7VqkZJrhQzcVXhg9Ov6k8vX1/v83oKAXUPuaOHhFwrzbvKrOgVtLxiFasq6gYGPF6emt1hE7y6JDRTAWtn3YdGKoGORs2DHRsPUKYDtfZRg7c9gW8XgcgLDF0iZm8oFIZPRXoedCn0J1fnVA5SKHByE3sizf7Df7l6vNYb7EYMMek8Og3ioVc45OdxSq1i5kKhnVdL0ou6rcVq6YPNx7XNeESBGYGFEcMzBPxoDlBjFPyHlMu8+S5yfr0q2n97iUfxIY/tEiRHjY4flnmjv61nobsdezq89TKHw914WU4qLXTVcU3NgsLnVGJTClxEqGWydqdFezgesfUwGB5eTyXbc2evouiOPP+e3QHuxaM1h40mCgTK7c4/csyofl9C6VAZIUNJqg1drvEjQom3Ppla8="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "YsAXZKBLEcLYV9xrz1JbVn6QK2T8GIOFe3FMuNlhR/kCZEkEfTKVpVbO5+4v82MUArtEeDXf84m5MmFsifEOJPm38IdxtBU3ausGcogOMKSnG0K2RILrddq4XXsu7JH1oKY1yzsaOcrXhTRfC9CoxBHCIz5GlQrwygtEPsqg3JjnHc6tldeSNa7/tLUCO7sUEy8SHcH3/voIQKa02fiwmmEN23YmgomBEFuFCTiWkDdBtYYw38WTGEwarZqXgi4TM1vmhuLPEwMqtjn4fdeZOi2oW9+6j8DcAhldJ/gkOLuGM3csN2zpA2DVALI3xERwXcOadnmaz6SJtx9ciebNIsm2mGEfng5x7LpmrOy8INfEGJXz5/We9keP2LZCzYWJUrp2ZXx6diSF6/nIhgUkiKRPHXHcPIoqvSFCEo7iuScwlOFVG+skBgCicRW/gzC9PHGsJbzc4ZqYZOdM+fXWi9HH6AdhJUjSR1AjmZfqdVuItRonQxsCJMaCqGyBgAgJ722n2KtuqWmtT2fG1KsPMw5PbmHQKcqhZdwnOQXHgZyB94YCirYRemjJ+cIiWG0xqThL2W6ECceX1tSz2FYOKUxSg+xmdzH3MCElNspMd6BDEf3efEDhOIBdWyQgCnOoooI7+Foz77b6eDbyKAcwo7bO7/UJOsSf3Edf5zJYmXI="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "Vn1md96LgHU4X2WnAwJv/mhLHaLkMwPa/B4xy+eIx/Mn3Fr6LOJVRMZnnYJfQPMXTQNyoenXDpVFuS2u25k5G5+lVGCCwVwnbtluOSewH1eZ/sdIIc/Q4d/w/DqiKV/gNiHrvkZkAjo/O2qJ9fi4cKoUfsXx+BT7lXRFHv4wV66UXqwz7VIVIYYEnNtvBdpW8/a3SedVHwYHU8LNvby4OKtUdk0bk6+IuxELHjZ8Ku67Qow0LmTcTrNRTSqDGIP7ZfaBK9Rb85DfnAG+heFUMr5gC1CY4YSRypHoy8HHuV9Jc+j6j+w2cwrE+6ntc7DAp9Af1Nlgn7I68cL254t3MJy7WMZAl83W+AwSClfyhwBu2jKFfVsaIOQryCZpjVBJdYFo+EuzwMS1MXpiadQI/LvVGJ5S0D2YCHkF7WROOYv6KsaS8xz5YdkZAPgj7c1RIP11Ah2Up6Gu/Ao3MBn54nNNsep4FIvmerNnEkbsTICvhWQfIF2HNBU0tevJIJYpt5KvcOG2iyGXjwRRdB9BuwiVWkUb58Z4Lq2Vg573LO/vggiZUdPBBTZmyIAaN7mk+8h7VRaWmB4z/HBePvlUftOoyukLaiSQAFnf41I4DIEQC/STZ3UK58fKUJNMH+DUMNY1Zr3gUGyloN25hB9OQW47fwV5nEEmHMtFV/I79Ic="
