# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  - $HOME/.m2

language: java

jdk: oraclejdk8

# Override default travis to use the maven wrapper
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean test -B
