# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "fI448ieGViV3SoFl+WlR5PtsBpqQnBdz394nXVKit+n6L09O7cUn07E7fVPf5wQpICEYziAcvu966I1ajUHhT6gf4h1SvjiRWE7GmLEc55ctBdofY5nbhMXtDQrD+pMu0Td3s/+vys3EduzynxugSzn0gSzLR7LWLySpgvhp+Pa7IAd6Z24K+Pxcrs88d/WSpGCcTJLmdXiA+UevRXX/SW4rM69y9uY1W2IWBbzN3Ev+5ylpJ5Lxp+uddmCThlAL7OB6SUHBWt6KmYA6xv5zq2DYsdpFVvwFRq3FZe4Nwh5vCidLz/Gdxk2c4z5PrJTHEoVSc3RSP1oI1E8ixaZm9RJhvmzgS0fdrSr4lm3oxvxepLnMW+OCXsFjCqc3F8DNBjGzWf8aD2EUj8fZSyr4Ffre1oRu6Y6PZErfyCDJ4qh1uxjlPdTE2s8K+yiTHYQ/xtP8sAz+7pZtXO5QgQljwpJshG4JYfs6Gsvxg/QK+NQfUCCCH4lGkc68k2xd5PFLo35kooS6zsq4OwmgGGW6wE/DNReZDndAj47yXLRpXVT3gjmbD0H5nwN7Pct5lw+SvE7yvqTrkS8rqFQSYvtboiXVKPVh3/JJHMHrFVAaQ/r6LH5uYaE275acOhYI4ASvDnM4vlrTps2enzM2XuEtJCtP45kTCzwqJ/teeeMysw8="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "aDtB8cBiLzXIUNXSzaMhd9y01KaVEwP9pBddk13d7ZEOvLibEt8sals/IOrrxrhPmfwrnO7EqJUOdz8rk6A4JFBzsp0iWVBPkvDOxy9zs4hiAKR3DZZl42D7ylBwMXSRW2VRYs/XlL+4qr25G9al5ClfP60pZmCJ6q9BSn5CdwNnBkQGXaS/W97pMZSxHt4lPK1kkNKclc81mWq0kZZ5VuAaH/LX2zAn90tu/+aEV5/MoivMjnyT4eZLl0uNOsjhLnK7YJqgj0kRwAqTBNqRW5hfHnWrD2mnuaPN4SE+4tfNESsCzAScSHWECPNHCIMEx2cecKQ9HTbzndnH6KJhrmkwiQ9CPOFhpkUXhCanmFLuagS2wHjMtAb5YtZPzgujArsyApoBWaHqVNHnDpw1GoH8sgImeCNq19Yho7QsRiDe1MPiOfTcUpFth+MiZOy9AG1MXntyymWJqhvMI4N032PhuwN9ZEIwCSakzG2jHlB1eL+b7IU9Atf2m4dZJosjF5l94v45Sc5N1/RUkNjcQqa2bURq7gjQR4SVoKrLZf/WoEwjTOz/nCT7pG14b6fOUef8yCdKAjzwOFlvXLxBYU+6W0zbLytoOOrEKTU6/4A1kBC76OnVdZg/W4g4St1KUvDnzWqZFyKZHhNDLOm/JfL5ZT0ERbjbWvTxrxczMAc="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "fDELe6BbxL6h24TMRjvvpQlymEnyMi5XI660mOxNV5OZ7PEGEE12o/dMx83GRupGIpAqAHFm0iSAuzofFDOXdsznedxT018KPYdkaFPGVDgfOYDaVNWeEoSIS6DbjADrTU7KS2e/aFQGpV95awvh5BTP2XxepoZIWw2ECXMsnInqg1u+IGoB5ydPZTPBmlpEhwgUFW/IGZNLodKbc8xSylfiDrDwH4NlqVJzWM0JjY7Xxt46b2NFqSbtGYj21gPaDOxmLJKIGMegeB/i1C63gONuAFBF/pgMTGISLH0O1AH48OImZa2pKFXstrAVofL1rstJjq20xNhnbzRgavc1Zobj+EhLFPPJSrG7FyiGWRVSIzkIYiMT2CXyAg5zNdV3HROd12AQhZ4bZ+UNF3Op0s+jpLfobyTm8meOq/HhF7AZwHSJfBzTA0cp5jD3CVMQjogKK9fYqiy834LsgrY81dVHBUb22tbumRpGc86EUpcmZ+NBbrOxCjk8gU6e2vXZ+NvPPtVJDIMq0JsNy/uhJJE9MzX4cfgP4YLpcPA62hxx1g0JQYmHeWNsoPhZhY8boPQrJCTBOChVf8RFIaWuLEg1ZEjT8qI8REBIXHyrXmA/2OG5qHYeak3xZ7QreI667nKQKhAIpO2Z2vqK5fbYvsvohAgbC6+H+NKGXNwbCKo="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "PtaGo8uoPEj9xWOnrQ4eLwUtZPS2/02i8gOgOH7aX45CzT/wwv1720bXekupApbe2TF81euMe6GzIzXgZIFKM64Vy55/caKnovKoW5Vys8vHZUzI/Bgo2721vJnD1p8vssFQ83nXoymMB4m+0p726ZQfYTDSxsrnN3vRaLXII9dEm+oQ2Uag1FbwgJ04sQnR8Y8xFuvaEOyEImFG9HTBjQub/WI7R8hY/+hRNKq47DeJ/n7D01NxZ6R+WLQOVQdzeCjtVa4bVVYiiTYURhzGRkSp2mEIBrEfYoatXoEagJu4abXufvSJG0e12/NMTFmI8F2MqKAgso7+ocXtYbTwdKxFsh3T8ydSE1VujjkvEdHHTY7iv2Cc31chwluTVRGCxBXClXeVKNskHkW0Zyru4qxP7QUrIEPtxrlSlLx7Q+yZmGBHGZHXh0wCEY/qQFdWzbVe8TmWwjoPwMPvmsK5Y9re1WX6Gm2xz2l5na3M+WXxvXtkK9jSBky+MXOk9t4vKvHc6fCouP3Q0ysUV7YegMoK4axbPu99H02RTMYBLcTqAlMcsWlvDUbSJJ9byLY9HzcgBIkQ8A+Drq2dUoUhUZGYytRkJ/eJqY7toL1pmu4BLnr5vRcOLzxtql2vKFqtdU9HT0ejzVIn2WpuFtbqsb1uS8RoQRIKNE7CG0+4i5g="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "hV6ZG4sZpPy6fgQR8r/jHaIRlp9PWGI4hBmIPjlVbFuH+QawRtrZtsiWai7U/20WSan/g92gdmPJzgnXr2PnCG/d97gK/gNL6qR+eGr6iJJmhCx4NnKE5mGevzAK0FDT6gnyOafqKph8K6SemAjpgc3YlBz3yOOc7gTzcdJlxLzG7xzBfU2wHmUxPt/I+6ZglYKtNV2NG7qSURMbjDXcexijzIC6TutZD7xKKBAN2JFv0BMkxsBXd1tb7stDyz5VfDl2Y0B/CLW7zLPY0i9TjbZ00cPdUKNFm5uTin1L4qWi77+DFk/+0pS5L1SQJsH+d5RPi+YmVRLhZInqWrDCu68Q5b63oxBWwGLgqh5InNUG/32yZrPLMp1C68CjTEjcEjEDAcdON2+A/oYSK+8gvFZvaOtGKH8hGnKWN6ZaXBBvPR7BptuKJ+pqa5OXr6ViwiC0IxAEIcpCGfXKrIpeiJfJAcJ8fywKtZ1AtYkbD8A49v/gUptvOjYfMFAN89sX0YkA0VNKxhhN9gOP1TvESt3+c33847fRFZZOHTwhzaqt4DX8ek9PGESAfNqXd6ja0CriTdp/ZmfD8rc/8u9xRNayQPScHpoRc4+EWTo62/OXiru5c7yZsoE1FeVuiibE0meLllRIa+Zbhn3BeGk2L4Yy359GjNz1mKr7TYCJ15k="
