# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

before_install:
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "qUKMggsfIR1mtPOoNlPSSFrUOOPVf0vgEucx10Prd5fojdzF4y950NaLoeLc0cHXBuq5DBc+vK93JqJUM7acS0jA/QLpwxK1pyPuy5TWHoDB6izdk1b36p17yy4SeFDGkP3VU0SBWO+rzNjUMe7kvCMJckoO7g1hlFXyEeL0f8IvWLSWMQO+1PX9COw2XCig9xc7rlOygORgIuLwjq3jb9+DEF+5KmZfhlVXqMs2hMOno0rB5DAqW3WD1uEiS57pxu0LQyqzQWDLsVSWH4iGV8VXM7LR2b1tKM6Kvc9s0Wu+6mP2xMNM5t+BGvARsYdElmZC/AqiGeKQ6En3kApzXfJ6PPvi8Dk+nUTXFSLnCo+4WrvovgSzJaaVpyknuhjmesPwrSiW8I86xeCsbwRnjkWQtIxJupCedK3jRlD7YpFMafU1dyJ5RWL+UO8kzUJn6hwZYWY5QBu0VUY8INP3P2mQe8DHBKNI8G8i43emCz1XmTipMErNcOlzDpgiqUlJhtc+saLAIeNSezWP7NbwHmrvVgqXD+Aoxa4FvBGl/WHwIeoQaUHmC6hR/2E4fHe/5G1UDDVdMt6H1j9aZxyYoz7+U/i9NgqL/QnQ0EVIwFRpoZYhGRkMn0+/08HSrs60cSZi8q+Akrqm+TiOTdODCthn3PWW09znfWJaxfXFH44="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "WfmbQP7Wh0ipeRHXqGMHZ6nXvHVp/FSnHTGYZZbZ174I7hsNIEHWpvzRq4fkzFWOJ6sJhle7Ye1o1jkTv+woLkVee0YoR8Vj12V3ojj6JwzXJsCBgBT3j2d4Dk5kdbOniJ7noB5znAjz+kcF7NaJP2IeV5BDUve7th3HSz9nJEY4uxtQVI7/qYjFnDBmqu9f4QFJ3rwVOiwAzAa7Oj5bNCPpbOkJKO+dcJh/oI7kUB+Yd77gwanE9WXjG/2AgASOmgW5k1rldOTybeeGZO7UmFV7QbCEnvvrBp+7M92lDul/1/JlOyV7Tt4o2Vux2d0JjgMbQ5pYc7NcIBMoud8VDJkjrBRkwIflGCThF7tCBt2DoLnpzomdsJ/ONzgqdJnXEPVoQS5YHN6mcvKIVnTBXSTB78yS7sEcyxzBfwHWoiszIlrvUklJJae8XDXfU5pK2OpZUtYJNkBp1WoZ9EO0b5AIITwMqncNBmBBsCVdEM9ruXxl8J2fcKqsWqKML/CeZD1sjx5l3+mji0JNNWCRYe/s/zUjQyijBZabsFMyWD5MOGcgZl2c5hSf2tiUVZXqtilch9jmrXTvsBWzBKXciCSS+bEKu0vnWcHL5tx+l13Kp/FppX6tcON0mnHskl6RNXAYIMsC2esxU5wlh/qoR+6ttGVN/6jNb7B2oJmV0W0="
  # Ex. travis encrypt GH_USER_EMAIL=for_github@domain.com --add
  - secure: "YRrFI0vcU9z84YOunt5/fRKMKA73KqtpnFCFeVPP7ar+FFWrOU/XCL1DvNHfpqGX3lb0+iPBrYQeMZhjFqqqFDcyu2usT1OdZdrlh+fZH0wgWQDAmIrJVH2nVXeT44aaSZo685G/47gBFiHgmAXU/Cpa9i1WBg6r+i0JII3HTeNFIGndID9SGPVaBLXMORySjkW8V1PcA0anfk0BJf0N8Hh0oUK5aM6MlZBpjqAApdg52J6RmejD7WFXPiJSpPapxc3NDXc6CIdSX4u7RvCtqLQrwlSpvMW/zNOtF/Y+SQ3VeKVs3+HtBajAq1v1Uk8TuYbepeiXArvqLSUkmEQwJ3I8UTgleATQYo83TlLAsuSA8uLcTfrufx6ITQDFhnOw5/gJTwtvCf8b1BEKlRc4KCgfFAJwTlan/AYiJlqi5SrbrlZAdfvO5pX0DXHy99uvX1AME3kzdlSgQ/nVeTrSbDyNcBV90VNohqDW3fMrIkUE0d6olQOp0pk4TFZ5Rzkw+sh0geJYy9IXUyfAl/dYiRylIM1+zP6WPgUuzEel1apFxEfD+ft8OHTkM7CFiuiANE4PMcrRZq/uE1N7Szm8aNRgPe/wfy+pmLS/sxJeBE/PhZMWZaW/c+kztCfNWyHoOi04Co0esejbFgghrpybJS7DR4nTj2t9fgA+tPblQiw="
  # Ex. travis encrypt GH_USER=your_github_account --add
  - secure: "V1WDmsefrYvuLMgs260wcE+WJTU8wygPwptBEu8Y9UaMgTBWHIyX3kZ6xo92SNNG9CnYTGIHGFeizhY0ZtI0dJ2kzKn3q9HsXN/HUZn8WXESmrN2AEyRLcjkVRr1+JfxzRt7Ef+gJJvx6n4XTMhqwI7AhVtMb1LRVQa5+12y39dopPLljXGI4w6AYYY5zq/kQ2BsqpAknxPWRi9D/fkAm5hpXkBXH6NBZXsm860I0aFMaM1hbvgBOZyA56xB6KUrJ5cF5SpQWrSsMQZ5qh0TpMwb+ZuXw1o7ihgBhfz07cdEGIadRrwYhM+2+Ckse54kBF4cHQYLV6fILxe/n7LY+7I2aKjAl4/rwQ/+RuWNNr5A768ImLKG8tNmdY1sIn8WzXlh68+jvJvLf4amfl60TA7wiU0EnvUAKyqrf+Z2ILWvbycnEiyLGFy0FLAeVncRltutWViebv9SoW8L/LaQOPjmzTWIVabG+AjOYJUz38T3aUAoiSj+nPxR7m5BHJJ8kadH1VQOoBj9CgF9Ey8lf9jJ3u6hMXuMjQB/Ci/QoBdMJcPJZ3vZXmkxmo46b+HDM9/NI1wqfBjZORITr6biDFoCdj/Pw/3zkPtvABT7/wY2mmmc2LfZywFrV+M4EKUDz10kkwjzSsleDJ09h1Q19c2qKYErogMMcdQBfsQnKng="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "GDV2LKG5Y12syK+fNtY/RY907uduudTWD/KgxzGqJLIHf2Iur+xcxBcCuaJ5Mucd0q1TUADVjHd3k1pmgab31AQtDG5oUcNgtLPSKE0tjWwRCBQScwF1GzPbhcZW9UgpspUfM9iA+mS9E4XgQnYpKQSAnqa9D3IgYFl3OjRkjYDGfAYNvae8JCGV0SpJmaPP3Lh5AYFcYx2p+Ab8fH+oi2jPoYT64L64yUvYErA49AEEvn1yiAGIdQQVxBLDEyXFHZGXgmMbIWNc5FtbtO5W9Q8LEsutqw1UjwHbGzrXlTkmOFCV3Ydp8rpOX7R7g79fqnTaqhau48N9twujU4jZgYJ+WzN8FfQmMEnkJJhi0WbCYE8HiF2hhk4k/rP+ZFsoUbe8qwbcFGTNkXSuvvmpOWsMbw6Zzcx27WzGrgeri2dSMGBBZ29cyHSmw8ArXEmf2lEBZVpaZ4J35Ml8YOtanQdmiFvRPsf+9Il/62sWKpv7ETvIbrE+ErzoRXw+fJcJMRCsfgK1lqppVGrPmAIl4RcauI02f7s27cnWxzjs7Byp236bVGHIEPeme9m3Y0OgfRIOnmAhV8sgeBKaGp09J/Ggb29o/VZ5GJtF7V7kDX/DqJ5qOfaZcFvQvj/r+OeVUKLvHgwvmoGV3/4D1EFVeKCcqap9DLQxoHzfs/0ig3I="
